SIM_OBJS=build/micaz/c-sf.o build/micaz/sf.o build/micaz/tossim.o build/micaz/c-support.o build/micaz/sim.o build/micaz/throttle.o 

SFDIR=$(TOSCONTRIB)/csm/tos/lib/tossim

all:
	g++ -g -c -o sim.o sim.c -I$(TOSDIR)/lib/tossim/ -I$(SFDIR)
	g++ -o sim sim.o $(SIM_OBJS)