/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'BigPackBlock'
 * message type.
 */

package edu.rice.wavelet.bigpack;

public class BigPackBlock extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 4;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = -1;

    /** Create a new BigPackBlock of size 4. */
    public BigPackBlock() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new BigPackBlock of the given data_length. */
    public BigPackBlock(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new BigPackBlock with the given data_length
     * and base offset.
     */
    public BigPackBlock(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new BigPackBlock using the given byte array
     * as backing store.
     */
    public BigPackBlock(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new BigPackBlock using the given byte array
     * as backing store, with the given base offset.
     */
    public BigPackBlock(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new BigPackBlock using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public BigPackBlock(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new BigPackBlock embedded in the given message
     * at the given base offset.
     */
    public BigPackBlock(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new BigPackBlock embedded in the given message
     * at the given base offset and length.
     */
    public BigPackBlock(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <BigPackBlock> \n";
      try {
        s += "  [start=0x"+Long.toHexString(get_start())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [length=0x"+Long.toHexString(get_length())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: start
    //   Field type: int, unsigned
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'start' is signed (false).
     */
    public static boolean isSigned_start() {
        return false;
    }

    /**
     * Return whether the field 'start' is an array (false).
     */
    public static boolean isArray_start() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'start'
     */
    public static int offset_start() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'start'
     */
    public static int offsetBits_start() {
        return 0;
    }

    /**
     * Return the value (as a int) of the field 'start'
     */
    public int get_start() {
        return (int)getUIntElement(offsetBits_start(), 16);
    }

    /**
     * Set the value of the field 'start'
     */
    public void set_start(int value) {
        setUIntElement(offsetBits_start(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'start'
     */
    public static int size_start() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'start'
     */
    public static int sizeBits_start() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: length
    //   Field type: int, unsigned
    //   Offset (bits): 16
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'length' is signed (false).
     */
    public static boolean isSigned_length() {
        return false;
    }

    /**
     * Return whether the field 'length' is an array (false).
     */
    public static boolean isArray_length() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'length'
     */
    public static int offset_length() {
        return (16 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'length'
     */
    public static int offsetBits_length() {
        return 16;
    }

    /**
     * Return the value (as a int) of the field 'length'
     */
    public int get_length() {
        return (int)getUIntElement(offsetBits_length(), 16);
    }

    /**
     * Set the value of the field 'length'
     */
    public void set_length(int value) {
        setUIntElement(offsetBits_length(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'length'
     */
    public static int size_length() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'length'
     */
    public static int sizeBits_length() {
        return 16;
    }

}
