COMPONENT=TestGraphAppC

TOSCONTRIBDIR=$(TOSROOT)/../tinyos-2.x-contrib/rice/tos

CFLAGS += -I$(TOSCONTRIBDIR)/lib/data/alloc
CFLAGS += -I$(TOSCONTRIBDIR)/lib/data/graph
CFLAGS += -I$(TOSCONTRIBDIR)/lib/data/list
CFLAGS += -I$(TOSCONTRIBDIR)/lib/data/queue

include $(MAKERULES)